import dayjs from 'dayjs'
export const categories = ['Watches', 'Smartphones', "TV's", 'Computers', 'Laptops']
export const categoriesWithSubcategories = [
	{
		category: 'Electronics',
		subcategories: [
			'Smartphones',
			'Laptops',
			'Tablets',
			'Cameras',
			'Headphones',
			'Smartwatches',
			'Televisions',
			'Gaming Consoles',
			'Accessories',
			'Home Appliances',
		],
	},
	{
		category: 'Groceries',
		subcategories: [
			'Fruits & Vegetables',
			'Meat & Poultry',
			'Dairy & Eggs',
			'Bakery',
			'Canned Goods',
			'Snacks',
			'Beverages',
			'Frozen Foods',
			'Condiments',
			'Household Essentials',
		],
	},
	{
		category: 'Fashion',
		subcategories: [
			"Men's Clothing",
			"Women's Clothing",
			"Kid's Clothing",
			'Shoes',
			'Accessories',
			'Bags',
			'Jewelry',
			'Watches',
			'Sportswear',
			'Underwear',
		],
	},
	{
		category: 'Home & Garden',
		subcategories: [
			'Furniture',
			'Tools',
			'Household Goods',
			'Gardening',
			'Home Decor',
			'Bedding & Bath',
			'Kitchen & Dining',
			'Lighting',
			'Outdoor Living',
			'Pet Supplies',
		],
	},
	{
		category: 'Health & Beauty',
		subcategories: [
			'Skin Care',
			'Hair Care',
			'Makeup',
			'Fragrances',
			'Personal Care',
			'Wellness',
			"Men's Grooming",
			'Beauty Tools',
			'Bath & Body',
			'Health Care',
		],
	},
	{
		category: 'Sports & Recreation',
		subcategories: [
			'Fitness',
			'Camping & Hiking',
			'Team Sports',
			'Outdoor Recreation',
			'Exercise Machines',
			'Cycling',
			'Water Sports',
			'Winter Sports',
			'Golf',
			'Athletic Shoes',
		],
	},
	{
		category: 'Automotive',
		subcategories: [
			'Car Parts',
			'Car Accessories',
			'Car Electronics',
			'Motorcycle Parts',
			'Motorcycle Accessories',
			'Oil & Fluids',
			'Tools & Equipment',
			'Tires & Wheels',
			'Exterior Accessories',
			'Interior Accessories',
		],
	},
	{
		category: 'Jewelry & Watches',
		subcategories: [
			'Fine Jewelry',
			'Fashion Jewelry',
			'Watches',
			"Men's Jewelry",
			"Women's Jewelry",
			'Wedding & Engagement',
			'Handmade Jewelry',
			"Kids' Jewelry",
			'Accessories',
			'Jewelry Storage',
		],
	},
	{
		category: 'Kids & Toys',
		subcategories: [
			'Toys & Games',
			"Kids' Clothing",
			'Baby Gear',
			"Kids' Shoes",
			'Baby Care',
			'Nursery',
			"Kids' Room",
			'Strollers & Car Seats',
			'Maternity',
			"Kids' Electronics",
		],
	},
	{
		category: 'Books & Media',
		subcategories: [
			'Books',
			'Movies',
			'Music',
			'Magazines',
			'Video Games',
			'E-books',
			'Audio Books',
			'TV Shows',
			'Podcasts',
			'Vinyl Records',
		],
	},
	{
		category: 'Furniture',
		subcategories: [
			'Living Room Furniture',
			'Bedroom Furniture',
			'Kitchen & Dining Furniture',
			'Home Office Furniture',
			'Outdoor Furniture',
			'Mattresses',
			'Accent Furniture',
			'Entryway Furniture',
			'Bathroom Furniture',
			"Kids' Furniture",
		],
	},
	{
		category: 'Tools',
		subcategories: [
			'Power Tools',
			'Hand Tools',
			'Tool Storage',
			'Measuring & Layout Tools',
			'Safety & Workwear',
			'Tool Sets',
			'Woodworking',
			'Automotive Tools',
			'Plumbing Tools',
			'Electrical Tools',
		],
	},
	{
		category: 'Pets',
		subcategories: [
			'Dog Supplies',
			'Cat Supplies',
			'Fish Supplies',
			'Bird Supplies',
			'Small Animal Supplies',
			'Reptile Supplies',
			'Pet Food',
			'Pet Treats',
			'Pet Beds & Furniture',
			'Pet Toys',
		],
	},
	{
		category: 'Alcohol',
		subcategories: [
			'Beer',
			'Wine',
			'Spirits',
			'Cocktails & Mixers',
			'Non-Alcoholic Drinks',
			'Cider',
			'Home Brewing & Wine Making',
			'Gifts',
			'Barware',
			'Accessories',
		],
	},
	{
		category: 'Musical Instruments',
		subcategories: [
			'Guitars',
			'Keyboards & MIDI',
			'Drums & Percussion',
			'Microphones',
			'Recording',
			'Live Sound',
			'DJ & Electronic Music',
			'Band & Orchestra',
			'Instrument Accessories',
			'Music Software',
		],
	},
	{
		category: 'Technology',
		subcategories: [
			'Computers & Tablets',
			'Networking',
			'Printers & Ink',
			'Software',
			'Accessories',
			'Smart Home',
			'Gadgets',
			'Office Electronics',
			'Cell Phones',
			'Security & Surveillance',
		],
	},
	{
		category: 'Office & School',
		subcategories: [
			'Office Supplies',
			'Office Furniture',
			'Stationery',
			'Calendars & Planners',
			'School Supplies',
			'Educational Toys',
			'Teaching Resources',
			'Art & Crafting',
			'Office Electronics',
			'Writing Instruments',
		],
	},
	{
		category: 'Household Goods',
		subcategories: [
			'Cleaning Supplies',
			'Storage & Organization',
			'Laundry Supplies',
			'Kitchen Essentials',
			'Disposable Tableware',
			'Home Fragrance',
			'Bathroom Essentials',
			'Air Fresheners',
			'Trash & Recycling',
			'Home Improvement',
		],
	},
	{
		category: 'Organic Food',
		subcategories: [
			'Fruits & Vegetables',
			'Dairy & Eggs',
			'Bakery',
			'Meat & Poultry',
			'Snacks',
			'Canned Goods',
			'Beverages',
			'Frozen Foods',
			'Condiments',
			'Household Essentials',
		],
	},
	{
		category: 'Consumer Electronics',
		subcategories: [
			'Smartphones',
			'Laptops',
			'Tablets',
			'Cameras',
			'Headphones',
			'Smartwatches',
			'Televisions',
			'Gaming Consoles',
			'Accessories',
			'Home Appliances',
		],
	},
	{
		category: 'Pawn',
		subcategories: [
			'Jewelry',
			'Electronics',
			'Tools',
			'Sporting Goods',
			'Musical Instruments',
			'Collectibles',
			'Antiques',
			'Firearms',
			'Coins & Currency',
			'Artwork',
		],
	},
	{
		category: 'Other',
		subcategories: ['Miscellaneous'],
	},
]
export const categoriesOfStores = [
	'Electronics',
	'Groceries',
	'Fashion',
	'Home & Garden',
	'Health & Beauty',
	'Sports & Recreation',
	'Automotive',
	'Jewelry & Watches',
	'Kids & Toys',
	'Books & Media',
	'Furniture',
	'Tools',
	'Pets',
	'Alcohol',
	'Musical Instruments',
	'Technology',
	'Office & School',
	'Household Goods',
	'Organic Food',
	'Consumer Electronics',
	'Pawn',
	'Other',
]
export const storesList = [
	'Own',
	'Other',
	'Allegro',
	'OLX',
	'Ceneo',
	'Gratka',
	'Nokaut',
	'eBay.pl',
	'Allegro Lokalnie',
	'Otomoto',
	'Zalando',
	'Domodi',
	'Amazon',
	'eBay',
	'AliExpress',
	'Walmart',
	'Shopify',
	'Taobao',
	'JD.com',
	'Etsy',
	'Rakuten',
	'Flipkart',
]
export const currencies = [
	'United States Dollar (USD)',
	'Euro (EUR)',
	'Japanese Yen (JPY)',
	'British Pound Sterling (GBP)',
	'Swiss Franc (CHF)',
	'Australian Dollar (AUD)',
	'Canadian Dollar (CAD)',
	'Norwegian Krone (NOK)',
	'Swedish Krona (SEK)',
	'Chinese Yuan (CNY)',
	'Russian Ruble (RUB)',
	'Indian Rupee (INR)',
	'Mexican Peso (MXN)',
	'Polish Zloty (PLN)',
	'New Zealand Dollar (NZD)',
	'Danish Krone (DKK)',
	'Czech Koruna (CZK)',
	'South Korean Won (KRW)',
	'Brazilian Real (BRL)',
	'Turkish Lira (TRY)',
]
const progressColors = {
	'0%': '#ff0000', // Czerwony
	'25%': '#ff6600', // Pomarańczowy
	'50%': '#ffff00', // Żółty
	'75%': '#00ff00', // Zielony
	'100%': '#008000', // Ciemnozielony
}
export const getStartAndEndOfWeek = () => {
	const today = dayjs()

	const currentDayOfWeek = today.day()

	const startOfCurrentWeek = today.subtract(currentDayOfWeek - 1, 'day').startOf('day')
	const endOfCurrentWeek = startOfCurrentWeek.add(6, 'day').endOf('day') //

	const startOfPreviousWeek = startOfCurrentWeek.subtract(7, 'day').startOf('day')
	const endOfPreviousWeek = endOfCurrentWeek.subtract(7, 'day').endOf('day') //

	return {
		currentWeek: { start: startOfCurrentWeek, end: endOfCurrentWeek },
		previousWeek: { start: startOfPreviousWeek, end: endOfPreviousWeek },
	}
}
